INITIAL_PLAYER_HEALTH = 5
LIST_OF_VARIANTS = ["WARRIOR", "ROBBER", "WIZARD"]
ATTACK_CH = """Choose a hero to attack:
1 - WARRIOR
2 - ROBBER
3 - WIZARD
"""
DEFENSE_CH = """Choose a hero to defense:
1 - WARRIOR
2 - ROBBER
3 - WIZARD
"""
WARNING_MSG = "Specify the number of the hero that corresponds to your choice!"
SUCCESSFUL_ATTACK_MSG = "YOUR ATTACK IS SUCCESSFUL!"
SUCCESSFUL_DEFENCE_MSG = "YOUR DEFENCE IS SUCCESSFUL!"
DRAW_MSG = "IT'S A DRAW!"
FAILED_ATTACK_MSG = "YOUR ATTACK IS FAILED!"
FAILED_DEFENCE_MSG = "YOUR DEFENCE IS FAILED!"

